# fly.toml app configuration file generated for api-quiet-rain-6700 on 2025-02-24T17:48:18-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'api-quiet-rain-6700'
primary_region = 'lax'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
